### ISSUE TITLE
Download links in Google/OneDrive/DropBox storage

### ISSUE THREAD

**Issue by abhishekaich27** [wanboyang/anomaly_detection_LAD2000#1]
Hi authors,

It would be great if you could make the all the files available via Google/OneDrive/DropBox storage. We are unable to access these files from Baidu.

Thank you for your time.

**Comment by wanboyang** [comment]
Thanks for your attention to our work. We will provide the downloading link from google drive in the next few days.

**Comment by wanboyang** [comment]
we have updated the downloading links from onedrive.
