### ISSUE TITLE
Feature/GT/Split files for custom dataset

### ISSUE THREAD

**Issue by abhishekaich27** [wanboyang/anomaly_detection_LAD2000#2]
Hi,

Thank you for providing the extracted features. I was wondering if I can create the same format files for a new dataset: **UCSD-Ped1**.

From your repo, I can create I3D features of UCSD-Ped1 using this link: https://github.com/wanboyang/anomly_feature.pytorch

Can you help me create the _GT_ files (_frame_label_IET.pickle, video_label_IET.pickle_), _train_split.txt_, and _test_split.txt_ for UCSD-Ped1 dataset?

**Comment by wanboyang** [comment]
UCSD-Ped1 and Ped2  datasets are too small to be divided into fixed training and test sets，following [work[1]](http://openaccess.thecvf.com/content_CVPR_2019/html/Zhong_Graph_Convolutional_Label_Noise_Cleaner_Train_a_Plug-And-Play_Action_Classifier_CVPR_2019_paper.html), k-fold cross-validation is recommended. 
Thanks for your attention.
[1] Jia-Xing Zhong, Nannan Li, Weijie Kong, Shan Liu, Thomas H. Li, Ge Li; Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2019, pp. 1237-1246
